exports.queryList = {
 ADD_USER_QUERY : `INSERT INTO SCP.USER(USERNAME, PASSWORD, EMAIL) VALUES($1, $2, $3) RETURNING USER_ID` ,
 FIND_USER_QUERY : `SELECT USER_ID, USERNAME, PASSWORD, EMAIL FROM SCP.USER WHERE (EMAIL = $1)`
}