exports.queryList = {
 ADD_USER_QUERY : `INSERT INTO SCP.USER(USERNAME, PASSWORD, EMAIL) VALUES($1, $2, $3) RETURNING USER_ID` ,
 FIND_USER_QUERY : `SELECT USER_ID, USERNAME, PASSWORD, EMAIL FROM SCP.USER WHERE (EMAIL = $1)`,
 CREATE_CART_USER_QUERY : `INSERT INTO SCP.CART (USER_ID) VALUES($1); `,

 ADD_PRODUCT_QUERY : `INSERT INTO SCP.PRODUCT (TITLE, PRICE, IMAGE_URL, DESCRIPTION,USER_ID) VALUES($1, $2, $3, $4, $5) RETURNING PRODUCT_ID`,
 GET_PROUDCT_DETAILS_QUERY : `SELECT PRODUCT_ID, TITLE, PRICE, IMAGE_URL, DESCRIPTION, USER_ID FROM SCP.PRODUCT WHERE (PRODUCT_ID = $1)`,
 UPDATE_PRODUCT_QUERY  : `UPDATE SCP.PRODUCT 
 SET TITLE=$1, PRICE=$2, IMAGE_URL=$3, DESCRIPTION=$4, USER_ID=$5
  WHERE PRODUCT_ID=$6
 `,
 GET_ALL_PROUDCTS_QUERY : `SELECT PRODUCT_ID, TITLE, PRICE, IMAGE_URL, DESCRIPTION, USER_ID FROM SCP.PRODUCT`,
 GET_ALL_PROUDCTS_PER_PAGE_QUERY : `SELECT PRODUCT_ID, TITLE, PRICE, IMAGE_URL, DESCRIPTION, USER_ID
 FROM SCP.PRODUCT
 LIMIT $1 OFFSET $2`,
 DELETE_PRODUCT_QUERY : `DELETE FROM scp.product WHERE product_id=$1; `,
 PRODUCT_COUNT_QUERY : `SELECT count(*) FROM SCP.PRODUCT`,
 GET_CART_QUERY : `SELECT CART_ID, USER_ID FROM SCP.CART WHERE USER_ID = $1 `,
 GET_PRODUCTS_FROM_CART_QUERY : `
 SELECT P.PRODUCT_ID, P.TITLE, C.QUANTITY 
FROM SCP.PRODUCT AS P
INNER JOIN SCP.CARTITEM AS C 
ON  P.PRODUCT_ID =  C.PRODUCT_ID
WHERE P.PRODUCT_ID = $1
 `,
 GET_PRODUCTS_FROM_USER_CART_QUERY : `
 SELECT P.PRODUCT_ID, P.TITLE, C.QUANTITY 
FROM SCP.PRODUCT AS P
INNER JOIN SCP.CARTITEM AS C 
ON  P.PRODUCT_ID =  C.PRODUCT_ID
WHERE C.CART_ID = $1
 `,
 INSERT_INTO_CARTITEMS_QUERY : `
 INSERT INTO SCP.CARTITEM
(QUANTITY,CART_ID,PRODUCT_ID)
VALUES($1,$2,$3);
`,
UPDATE_CARTITEMS_QUERY : `
UPDATE SCP.CARTITEM
SET QUANTITY=$1
WHERE CART_ID= $2 AND PRODUCT_ID = $3;
`,
DELETE_PRODUCT_FROM_CARTITEM_QUERY : `DELETE FROM SCP.CARTITEM
WHERE PRODUCT_ID= $1 AND CART_ID  = $2;`
}